services:
  database:
    volumes:
      - mysql:/var/lib/mysql
    container_name: kcg-app-db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT:-3306}:3306
    networks:
      net:

  php:
    volumes:
      - ./project/backend:/var/www/html
    container_name: kcg-cli-php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
        TIMEZONE: ${TIMEZONE}
    depends_on:
      - "database"
    networks:
      net:

  ws-backend:
    volumes:
      - ./project/backend:/var/www/html
      - ./docker/nginx/backend.conf:/etc/nginx/conf.d/default.conf
    container_name: kcg-app-wsbackend
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        PORT: 8080
        TIMEZONE: ${TIMEZONE}
    ports:
      - "${BACKEND_PORT:-8080}:8080"
    depends_on:
      - "php"
    networks:
      net:

  composer:
    volumes:
      - ./project/backend:/app
    container_name: kcg-cli-composer
    build:
      context: .
      dockerfile: ./docker/composer/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
        TIMEZONE: ${TIMEZONE}
    depends_on:
      - "ws-backend"
    networks:
      net:

  node:
    volumes:
      - ./project/frontend:/app
    container_name: kcg-cli-node
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
        TIMEZONE: ${TIMEZONE}
    depends_on:
      - "ws-backend"
    networks:
      net:

  ws-frontend:
    volumes:
      - ./project/frontend:/var/www/html
      - ./docker/nginx/frontend.conf:/etc/nginx/conf.d/default.conf
    container_name: kcg-app-wsfrontend
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
      args:
        PORT: 80
        TIMEZONE: ${TIMEZONE}
    ports:
      - "${FRONTEND_PORT:-80}:80"
    depends_on:
      - "node"
    networks:
      net:

networks:
  net:
    name: kcg-project-network
    external: false

volumes:
  mysql:
    name: kcg-db-data